spring.application.name=student-record-management
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/studentdb}
# spring.datasource.driverClassName is removed to allow auto-detection

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=${PORT:8081}
spring.jpa.hibernate.ddl-auto=update
